export const routes = {
  login: "/api/users/login",
  register: "/api/users/register",
  loggedUser: "/api/users/me",
  updateLoggedUser: "/api/users/updateMe",
  updatePassword: "/api/users/updatePassword",
  users: "/api/users",
  category: "/api/category",
  settings: "/api/settings",
  singleUpload: "/api/image/upload",
  multiUpload: "/api/image/multiple-upload",
  deleteUpload: "/api/image/delete",
  size: "/api/size",
  coupon: "/api/coupon",
  product: "/api/product",
  payment: "/api/payment",
  order: "/api/order",
};
